-- Replace CHANGE_ME_LOCAL_PASSWORD before running this script.
CREATE USER IF NOT EXISTS 'tianmu'@'%' IDENTIFIED BY 'CHANGE_ME_LOCAL_PASSWORD';
ALTER USER 'tianmu'@'%' IDENTIFIED BY 'CHANGE_ME_LOCAL_PASSWORD';
GRANT ALL PRIVILEGES ON `tianmu`.* TO 'tianmu'@'%';
FLUSH PRIVILEGES;
